# Generated by Django 4.2.2 on 2023-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_gender', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=100)),
                ('date_of_join', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('emp_shift', models.CharField(max_length=100)),
                ('emp_cate', models.CharField(max_length=100)),
                ('emp_bio', models.CharField(max_length=100)),
                ('emp_head', models.CharField(max_length=100)),
                ('emp_skill', models.CharField(blank=True, choices=[('skill A', 'skill A'), ('skill B', 'skill B'), ('skill C', 'skill C'), ('skill D', 'skill D'), ('skill E', 'skill E')], max_length=255, null=True)),
                ('emp_img', models.ImageField(upload_to='static/img/')),
                ('martial', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('emp_age', models.CharField(max_length=100)),
                ('blood_grp', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('activities', models.CharField(max_length=100)),
                ('disability', models.CharField(max_length=100)),
                ('emp_country', models.CharField(max_length=100)),
                ('emp_state', models.CharField(max_length=100)),
                ('emp_district', models.CharField(max_length=100)),
                ('buliding_no', models.CharField(max_length=100)),
                ('emp_street', models.CharField(max_length=100)),
                ('emp_area', models.CharField(max_length=100)),
                ('emp_pincode', models.CharField(max_length=100)),
                ('emp_p_country', models.CharField(max_length=100)),
                ('emp_p_state', models.CharField(max_length=100)),
                ('emp_p_district', models.CharField(max_length=100)),
                ('p_buliding_no', models.CharField(max_length=100)),
                ('emp_p_street', models.CharField(max_length=100)),
                ('emp_p_area', models.CharField(max_length=100)),
                ('emp_p_pincode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='typeCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_type', models.CharField(max_length=100)),
                ('Item_rate', models.CharField(max_length=100)),
                ('Item_code', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
