# Generated by Django 4.2.2 on 2023-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0002_masterpage_typecreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Random_Number_alpha', models.CharField(max_length=100)),
                ('Invoice_Number', models.CharField(max_length=100)),
                ('Name_ID', models.CharField(max_length=100)),
                ('Bill_Date_alpha', models.DateField()),
                ('Item_Type', models.CharField(max_length=100)),
                ('Item_Code', models.CharField(max_length=100)),
                ('Item_Rate', models.CharField(max_length=100)),
                ('Quantity_alpha', models.CharField(max_length=100)),
                ('Total_alpha', models.CharField(max_length=100)),
            ],
        ),
    ]
