# Generated by Django 4.2.2 on 2023-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0003_mainbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Random_Number_beta', models.CharField(max_length=100)),
                ('Invoice_Number_beta', models.CharField(max_length=100)),
                ('Name_ID_beta', models.CharField(max_length=100)),
                ('Bill_Date_beta', models.DateField()),
                ('All_Quantity_beta', models.CharField(max_length=100)),
                ('All_Total_beta', models.CharField(max_length=100)),
            ],
        ),
    ]
