# Generated by Django 4.2.2 on 2023-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0004_invoice_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='Name_ID_beta',
            field=models.IntegerField(max_length=100),
        ),
    ]
