# Generated by Django 4.2.2 on 2023-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0005_alter_invoice_details_name_id_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbill',
            name='Name_ID',
            field=models.IntegerField(max_length=100),
        ),
    ]
