# Generated by Django 4.2.2 on 2023-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0006_alter_mainbill_name_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('Item_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=100)),
                ('P_Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('P_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
