# Generated by Django 4.2.2 on 2023-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorapp', '0009_accessoriesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='addCountryModel',
            fields=[
                ('Country_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='addDistrictModel',
            fields=[
                ('District_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=100)),
                ('State_Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='addStateModel',
            fields=[
                ('State_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('State_Name', models.CharField(max_length=100)),
                ('Country_Id', models.IntegerField()),
            ],
        ),
    ]
